language: php
php:
  - "5.5"
  - "5.4"
before_script:
  - composer install --prefer-dist --dev --no-interaction
script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs --encoding=utf-8 --extensions=php --standard=phpcs.xml -sp .
after_script:
  - vendor/bin/coveralls -v

